apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-depl
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app # This is connection between the deployment and the pod specified below
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: njnisarg/kube-auto-scaler:web_app
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 150000Ki
          requests:
            cpu: 300m
            memory: 150000Ki
        ports:
        - containerPort: 3000 # The port inside the container opened for listening
        
