apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-depl
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app # This is connection between the deployment and the pod specified below
  template:
    metadata:
      name: web-app-depl-pod
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: yeasy/simple-web
        resources:
          limits:
            cpu: 1000m
            memory: 200000Ki
          requests:
            cpu: 250m
            memory: 100000Ki
        ports:
        - containerPort: 80 # The port inside the container opened for listening
        
