apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-depl
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app # This is connection between the deployment and the pod specified below
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: yeasy/simple-web
        ports:
        - containerPort: 80 # The port inside the container opened for listening
        
