apiVersion: v1
kind: Namespace
metadata:
  name: web-app
  labels: 
    name: web-app
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-cpu-request: 250m
    config.linkerd.io/proxy-memory-request: 100000Ki