apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # The port opened for listening
      targetPort: 80 # The port on the pod to forward the request 
      nodePort: 30001 # The port of the node to be exposed